# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-10 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundHausII', '0002_auto_20180207_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
